/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samudra~
 */
public class koversi_suhu extends javax.swing.JFrame {

    /**
     * Creates new form koversi_suhu
     */
    public koversi_suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfHCelcius = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CR = new javax.swing.JButton();
        CK = new javax.swing.JButton();
        HCelcius = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tfCelcius = new javax.swing.JTextField();
        CF = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfHKelvin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        KR = new javax.swing.JButton();
        KC = new javax.swing.JButton();
        HKelvin = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tfKelvin = new javax.swing.JTextField();
        KF = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfHReamur = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        RK = new javax.swing.JButton();
        RC = new javax.swing.JButton();
        HReamur = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tfReamur = new javax.swing.JTextField();
        RF = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfHFahrenheit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FR = new javax.swing.JButton();
        FC = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tfFahrenheit = new javax.swing.JTextField();
        FK = new javax.swing.JButton();
        HFahrenheit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplikasi Konversi Suhu");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 80));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ke");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tfHCelcius.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel4.add(tfHCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hasil :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Konversi dari Celcius");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        CR.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CR.setText("Reamur");
        CR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRActionPerformed(evt);
            }
        });
        jPanel4.add(CR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        CK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CK.setText("Kelvin");
        CK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKActionPerformed(evt);
            }
        });
        jPanel4.add(CK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        HCelcius.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        HCelcius.setText("Hapus");
        HCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCelciusActionPerformed(evt);
            }
        });
        jPanel4.add(HCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Celcius :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tfCelcius.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel4.add(tfCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, -1));

        CF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CF.setText("Fahrenheit");
        CF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFActionPerformed(evt);
            }
        });
        jPanel4.add(CF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 440, 140));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        btnExit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 930, 50));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 930, 10));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ke");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tfHKelvin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel8.add(tfHKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hasil :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Konversi dari Kelvin");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        KR.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        KR.setText("Reamur");
        KR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KRActionPerformed(evt);
            }
        });
        jPanel8.add(KR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        KC.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        KC.setText("Celcius");
        KC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KCActionPerformed(evt);
            }
        });
        jPanel8.add(KC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        HKelvin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        HKelvin.setText("Hapus");
        HKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HKelvinActionPerformed(evt);
            }
        });
        jPanel8.add(HKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Kelvin :");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tfKelvin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel8.add(tfKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, -1));

        KF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        KF.setText("Fahrenheit");
        KF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KFActionPerformed(evt);
            }
        });
        jPanel8.add(KF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 440, 140));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ke");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tfHReamur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel11.add(tfHReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Hasil :");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Konversi dari Reamur");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        RK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RK.setText("Kelvin");
        RK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RKActionPerformed(evt);
            }
        });
        jPanel11.add(RK, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        RC.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RC.setText("Celcius");
        RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCActionPerformed(evt);
            }
        });
        jPanel11.add(RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        HReamur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        HReamur.setText("Hapus");
        HReamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HReamurActionPerformed(evt);
            }
        });
        jPanel11.add(HReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Reamur :");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tfReamur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel11.add(tfReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, -1));

        RF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RF.setText("Fahrenheit");
        RF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFActionPerformed(evt);
            }
        });
        jPanel11.add(RF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 440, 140));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ke");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tfHFahrenheit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel10.add(tfHFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hasil :");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Konversi dari Fahrenheit");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        FR.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        FR.setText("Reamur");
        FR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRActionPerformed(evt);
            }
        });
        jPanel10.add(FR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        FC.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        FC.setText("Celcius");
        FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCActionPerformed(evt);
            }
        });
        jPanel10.add(FC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fahrenheit :");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tfFahrenheit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel10.add(tfFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, -1));

        FK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        FK.setText("Kelvin");
        FK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FKActionPerformed(evt);
            }
        });
        jPanel10.add(FK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        HFahrenheit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        HFahrenheit.setText("Hapus");
        HFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HFahrenheitActionPerformed(evt);
            }
        });
        jPanel10.add(HFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 440, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRActionPerformed
        Double celcius = Double.parseDouble(String.valueOf(tfCelcius.getText()));
        Double reamur = celcius * 0.8;
        tfHCelcius.setText(String.valueOf(reamur) + " ° Ré");
    }//GEN-LAST:event_CRActionPerformed

    private void CKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKActionPerformed
        Double celcius = Double.parseDouble(String.valueOf(tfCelcius.getText()));
        Double kelvin = celcius + 273.15;
        tfHCelcius.setText(String.valueOf(kelvin) + " ° K");
    }//GEN-LAST:event_CKActionPerformed

    private void HCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCelciusActionPerformed
        tfCelcius.setText(null);
        tfHCelcius.setText(null);
    }//GEN-LAST:event_HCelciusActionPerformed

    private void CFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFActionPerformed
        Double celcius = Double.parseDouble(String.valueOf(tfCelcius.getText()));
        Double fahrenheit = celcius * 1.8 + 32;
        tfHCelcius.setText(String.valueOf(fahrenheit) + " ° F");
    }//GEN-LAST:event_CFActionPerformed

    private void KRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KRActionPerformed
        Double kelvin = Double.parseDouble(String.valueOf(tfKelvin.getText()));
        Double reamur = (kelvin - 273.15) * 0.8;
        tfHKelvin.setText(String.valueOf(reamur) + " ° Ré");
    }//GEN-LAST:event_KRActionPerformed

    private void KCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KCActionPerformed
        Double kelvin = Double.parseDouble(String.valueOf(tfKelvin.getText()));
        Double celcius = kelvin - 273.15;
        tfHKelvin.setText(String.valueOf(celcius) + " ° C");
    }//GEN-LAST:event_KCActionPerformed

    private void HKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HKelvinActionPerformed
        tfKelvin.setText(null);
        tfHKelvin.setText(null);
    }//GEN-LAST:event_HKelvinActionPerformed

    private void KFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KFActionPerformed
        Double kelvin = Double.parseDouble(String.valueOf(tfKelvin.getText()));
        Double fahrenheit = kelvin * 1.8 - 459.67;
        tfHKelvin.setText(String.valueOf(fahrenheit) + " ° F");
    }//GEN-LAST:event_KFActionPerformed

    private void FRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRActionPerformed
        Double fahrenheit = Double.parseDouble(String.valueOf(tfFahrenheit.getText()));
        Double reamur = (fahrenheit - 32) / 2.25;
        tfHFahrenheit.setText(String.valueOf(reamur) + " ° Ré");
    }//GEN-LAST:event_FRActionPerformed

    private void FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCActionPerformed
        Double fahrenheit = Double.parseDouble(String.valueOf(tfFahrenheit.getText()));
        Double celcius = (fahrenheit - 32) / 1.8;
        tfHFahrenheit.setText(String.valueOf(celcius) + " ° C");
    }//GEN-LAST:event_FCActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void FKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FKActionPerformed
        Double fahrenheit = Double.parseDouble(String.valueOf(tfFahrenheit.getText()));
        Double kelvin = (fahrenheit + 459.67) / 1.8;
        tfHFahrenheit.setText(String.valueOf(kelvin) + " ° K");
    }//GEN-LAST:event_FKActionPerformed

    private void RKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RKActionPerformed
        Double reamur=Double.parseDouble(String.valueOf(tfReamur.getText()));
        Double kelvin=reamur/0.8+273.15;
        tfHReamur.setText(String.valueOf(kelvin) + " ° K");
    }//GEN-LAST:event_RKActionPerformed

    private void RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCActionPerformed
        Double reamur=Double.parseDouble(String.valueOf(tfReamur.getText()));
        Double celcius=reamur/0.8;
        tfHReamur.setText(String.valueOf(celcius) + " ° C");
    }//GEN-LAST:event_RCActionPerformed

    private void HReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HReamurActionPerformed
        tfReamur.setText(null);
        tfHReamur.setText(null);
    }//GEN-LAST:event_HReamurActionPerformed

    private void RFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFActionPerformed
        Double reamur=Double.parseDouble(String.valueOf(tfReamur.getText()));
        Double fahrenheit=reamur*2.25+32;
        tfHReamur.setText(String.valueOf(fahrenheit) + " ° F");
    }//GEN-LAST:event_RFActionPerformed

    private void HFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HFahrenheitActionPerformed
        tfFahrenheit.setText(null);
        tfHFahrenheit.setText(null);
    }//GEN-LAST:event_HFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koversi_suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koversi_suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koversi_suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koversi_suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koversi_suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CF;
    private javax.swing.JButton CK;
    private javax.swing.JButton CR;
    private javax.swing.JButton FC;
    private javax.swing.JButton FK;
    private javax.swing.JButton FR;
    private javax.swing.JButton HCelcius;
    private javax.swing.JButton HFahrenheit;
    private javax.swing.JButton HKelvin;
    private javax.swing.JButton HReamur;
    private javax.swing.JButton KC;
    private javax.swing.JButton KF;
    private javax.swing.JButton KR;
    private javax.swing.JButton RC;
    private javax.swing.JButton RF;
    private javax.swing.JButton RK;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField tfCelcius;
    private javax.swing.JTextField tfFahrenheit;
    private javax.swing.JTextField tfHCelcius;
    private javax.swing.JTextField tfHFahrenheit;
    private javax.swing.JTextField tfHKelvin;
    private javax.swing.JTextField tfHReamur;
    private javax.swing.JTextField tfKelvin;
    private javax.swing.JTextField tfReamur;
    // End of variables declaration//GEN-END:variables
}
